//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineOSForms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApbdEntities : DbContext
    {
        public ApbdEntities()
            : base("name=ApbdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinema> Cinema { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Projection> Projection { get; set; }
        public virtual DbSet<ProjectionRoom> ProjectionRoom { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Work> Work { get; set; }
    }
}
