//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineOSForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectionRoom
    {
        public ProjectionRoom()
        {
            this.Projection = new HashSet<Projection>();
        }
    
        public int Id { get; set; }
        public int IdCinema { get; set; }
        public string Name { get; set; }
        public string RoomNumber { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual ICollection<Projection> Projection { get; set; }
    }
}
