//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineOSForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projection
    {
        public Projection()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Length { get; set; }
        public int IdProjectionRoom { get; set; }
    
        public virtual ProjectionRoom ProjectionRoom { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
