//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineOSForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int IdEmployee { get; set; }
        public int IdCinema { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
